# Generated by Django 3.2 on 2021-04-29 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_reg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='creator',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
