# Generated by Django 3.2 on 2021-04-29 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_reg', '0002_task_creator'),
    ]

    operations = [
        migrations.DeleteModel(
            name='task',
        ),
    ]
