# Generated by Django 3.2 on 2021-04-30 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=1000)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
